LEVEL=../../..
LIBRARYNAME=DaikonPass
LOADABLE_MODULE=1
ENABLE_OPTIMIZE=0
CFLAGS += -Wunused-variable
CXXFLAGS += -std=c++0x -fexceptions
#CXXFLAGS += -I$$boost_lib 
include $(LEVEL)/Makefile.common

